### ISSUE TITLE
StartEvictor leaks go-routines and also has race conditions that could cause a crash

### ISSUE THREAD

**Issue by deepakprabhakara** [jolestar/go-commons-pool#18]
Calling StartEvictor multiple times causes a leak since the go-routine doesn't get closed (ticket.Stop() does not close the channel). 

Also if StartEvictor is called in succession it could lead to a race condition which causes a crash in line 511 of pool.go since pool.evictor can be set to nil before the range starts.

**Comment by philoles** [comment]
import "context"

add 
`evictorCancelFunc                context.CancelFunc`
to ObjectPool

change startEvictor

`func (pool *ObjectPool) startEvictor(delay int64) {
	ctx, cancel := context.WithCancel(context.Background())

	if pool.evictorCancelFunc == nil {
		pool.evictorCancelFunc = cancel
	} else {
		pool.evictorCancelFunc()
		pool.evictorCancelFunc = cancel
	}

	if delay > 0 {
		pool.evictionLock.Lock()
		pool.evictor = time.NewTicker(time.Duration(delay) * time.Millisecond)
		pool.evictionLock.Unlock()

		go func() {
			for {
				select {
				case <-ctx.Done():
					pool.evictionLock.Lock()
					pool.evictor.Stop()
					pool.evictor = nil
					pool.evictionIterator = nil
					pool.evictionLock.Unlock()
					return
				case <-pool.evictor.C:
					pool.evict()
					pool.ensureMinIdle()
				}
			}
		}()
	}
}`
