### ISSUE TITLE
Context Support

### ISSUE THREAD

**Issue by dcormier** [jolestar/go-commons-pool#24]
It would be nice if `context.Context` could be passed to methods on the pool, and also if the context was passed to the factory methods.

I already have a PR that adds a `BorrowWithContext` method that will cancel based on the supplied context (#26), but this is only a first step.

If the author is willing to break backwards compatibility (which means releasing this as v2.0.0), I can change the package to pass a context down all the way to the factory methods.

**Comment by dcormier** [comment]
I have [another branch](https://github.com/dcormier/go-commons-pool/tree/dc/morectx) where I'm doing more work to modernize this to support context. This branch breaks backwards compatibility, but only in that a context must now be passed to `BorrowObject` and a few other methods like `AddObject`. As of right now, all the tests pass.

**Comment by jolestar** [comment]
Finished by https://github.com/jolestar/go-commons-pool/pull/26
